### ISSUE TITLE
Latin American flags

### ISSUE THREAD

**Issue by hectorpalmatellez** [dthms/sassy-flags#1]
Could you add some Latin American flags?
Like Brazil, Chile, Colombia…

**Comment by dthms** [comment]
Hey Hector,

They will be online tomorrow! ;)

Have a good day

**Comment by hectorpalmatellez** [comment]
@dthms :clap: :clap: :clap: :clap: :clap: 
¡Gracias!

**Comment by AlexBuitrago** [comment]
Hey! I don't know if this is the better place to put this, but I wrote the flag for my country. I tried to follow the general style of the other flags. In fact is a fork of the Colombian one: http://jsbin.com/qamuheyusi/1/
